'use client';
import { useState } from 'react';
import Link from 'next/link';
import { foodMenu } from '@/content/menu';
export function GuestExperience({kind}:{kind:'reservation'|'order'}) {
 const [done,setDone]=useState(false); const [count,setCount]=useState(2); const [cart,setCart]=useState<Record<string,number>>({});
 const dishes=foodMenu.categories.flatMap(c=>c.items).filter(i=>['spicy-rigatoni','chicken-parmigiana','burrata','tiramisu'].includes(i.id));
 const total=dishes.reduce((sum,item)=>sum+(item.priceCents??0)*(cart[item.id]??0),0);
 if(done)return <section className="mx-auto max-w-2xl px-6 py-20"><p className="eyebrow">Demo confirmation</p><h1 className="display mt-4 text-5xl">{kind==='reservation'?'Your imaginary table is ready.':'A very good choice.'}</h1><p className="mt-6 leading-relaxed">{kind==='reservation'?`Sample reservation for ${count} guests.`:`Sample order total: $${(total/100).toFixed(2)}.`} No real booking or order was placed. No payment or email was sent.</p><div className="mt-8 flex gap-6"><button className="cn-button" onClick={()=>setDone(false)}>Try another {kind}</button><Link className="cn-text-link" href="/demo/admin">Explore the admin</Link></div></section>;
 return <section className="mx-auto max-w-3xl px-6 py-16"><p className="eyebrow">Cosa Nostra · A sample evening</p><h1 className="display mt-3 text-5xl sm:text-6xl">{kind==='reservation'?'There’s a table with your name on it.':'Bring a little of the evening home.'}</h1><p className="my-6 leading-relaxed">This is an interactive portfolio demo. Try the experience with sample details; nothing is booked, charged or sent.</p><form onSubmit={e=>{e.preventDefault();setDone(true)}} className="grid gap-5">
 {kind==='reservation'?<><label className="grid gap-2 text-sm">Party size<select value={count} onChange={e=>setCount(Number(e.target.value))} className="rounded border border-current/25 bg-transparent p-3">{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} guests</option>)}</select></label><label className="grid gap-2 text-sm">Date<input aria-label="Reservation date" type="date" required min={new Date().toLocaleDateString('en-CA',{timeZone:'America/Chicago'})} className="min-w-0 rounded border border-current/25 bg-transparent p-3"/></label><label className="grid gap-2 text-sm">Time<select className="rounded border border-current/25 bg-transparent p-3">{['5:00 PM','5:30 PM','6:00 PM','6:30 PM','7:00 PM','7:30 PM','8:00 PM','8:30 PM'].map(t=><option key={t}>{t}</option>)}</select></label><label className="grid gap-2 text-sm">Sample guest name<input defaultValue="Jamie Morgan" required maxLength={60} className="rounded border border-current/25 bg-transparent p-3"/></label></>:<><div className="divide-y divide-current/20">{dishes.map(item=><div key={item.id} className="flex items-center justify-between gap-4 py-5"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm">${((item.priceCents??0)/100).toFixed(2)}</p></div><label className="flex items-center gap-3 text-sm"><span className="sr-only">Quantity for {item.name}</span><select aria-label={`Quantity for ${item.name}`} value={cart[item.id]??0} onChange={e=>setCart({...cart,[item.id]:Number(e.target.value)})} className="rounded border border-current/25 bg-transparent p-3">{[0,1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label></div>)}</div><p className="text-xl">Sample total: ${(total/100).toFixed(2)}</p></>}
 <button className="cn-button justify-center" disabled={kind==='order'&&total===0}>Preview {kind==='reservation'?'reservation':'order'} confirmation →</button></form></section>;
}
