import type { AssetKind } from './assets';
import type { PublicAsset } from './media';

/**
 * Shipped website key art, by event slug.
 *
 * The same arrangement the seasonal theme uses: the repository ships artwork,
 * the admin can upload their own into the same slot, and an upload always wins.
 * A slug with no entry simply has no default, which is a perfectly normal state
 * — the event then shows its official flyer, which is the point.
 *
 * These files are SECONDARY art. They are backgrounds the site composes around
 * an event; they are never that event's flyer and never replace one.
 * Generated by `npx tsx scripts/generate-event-art.ts`.
 */

const DIR = '/events';

/** Slugs that ship with a background. Everything else falls back to the flyer. */
const SLUGS = ['vinyl-vermouth','sunday-supper','after-hours-friday','after-hours-saturday','aperitivo-club'] as const;

const SPARES: string[] = [];


const SHIPPED_FLYERS: Record<string, { width:number; height:number }> = {};

/** Every shipped flyer file, for the docs. */
export const EVENT_FLYER_FILES: string[] = Object.keys(SHIPPED_FLYERS).map(
  (slug) => `${DIR}/flyers/${slug}.jpg`,
);

/** Every shipped file, for the asset check and the docs. */
export const EVENT_ART_FILES: string[] = [...SLUGS, ...SPARES].flatMap((slug) => [
  `${DIR}/${slug}.webp`,
  `${DIR}/${slug}-640.webp`,
  `${DIR}/${slug}-tall.webp`,
  `${DIR}/${slug}-tall-448.webp`,
]);

/**
 * A shipped background, with the widths it exists at.
 *
 * `srcSet` is the whole reason these are plain `<img>` elements rather than
 * `next/image`: art direction between the wide and upright crops needs
 * `<picture>`, and `<picture>` needs the widths written out.
 */
export interface EventArtImage extends PublicAsset {
  srcSet: string;
}

function asset(
  path: string,
  width: number,
  height: number,
  ratio: string,
  small: { path: string; width: number },
): EventArtImage {
  return {
    srcSet: `${small.path} ${small.width}w, ${path} ${width}w`,
    path,
    kind: 'image' as AssetKind,
    // Decorative by definition: everything it conveys — the event's name, date,
    // price and status — is rendered beside it as real text.
    alt: null,
    width,
    height,
    ratio,
    focal: '50% 45%',
    status: 'final',
  };
}

export interface DefaultEventArt {
  wide: EventArtImage;
  tall: EventArtImage;
}

const DEFAULTS: Record<string, DefaultEventArt> = Object.fromEntries(
  [...SLUGS, ...SPARES].map((slug) => [
    slug,
    {
      wide: asset(`${DIR}/${slug}.webp`, 1600, 900, '16:9', {
        path: `${DIR}/${slug}-640.webp`,
        width: 640,
      }),
      tall: asset(`${DIR}/${slug}-tall.webp`, 900, 1125, '4:5', {
        path: `${DIR}/${slug}-tall-448.webp`,
        width: 448,
      }),
    },
  ]),
);

/** The shipped art for an event, or null when it has none. */
export function defaultEventArt(slug: string | null): DefaultEventArt | null {
  if (!slug) return null;
  const aliases: Record<string,string> = {'vinyl-vermouth-session':'vinyl-vermouth','sunday-supper-special':'sunday-supper','pasta-night':'sunday-supper'};
  return DEFAULTS[aliases[slug] ?? slug] ?? null;
}

/**
 * The OFFICIAL flyer that ships for an event, or null.
 *
 * `title` is only used to describe the picture: a flyer carries the event's
 * name, date and price in its pixels, so it is never decorative and always
 * gets real alt text.
 */
export function defaultEventFlyer(slug: string | null, title: string): PublicAsset | null {
  if (!slug) return null;
  const size = SHIPPED_FLYERS[slug];
  if (!size) return null;
  return {
    path: `${DIR}/flyers/${slug}.jpg`,
    kind: 'image' as AssetKind,
    alt: `Official flyer for ${title}`,
    width: size.width,
    height: size.height,
    ratio: `${size.width}:${size.height}`,
    focal: '50% 50%',
    status: 'final',
  };
}
